# Ficha Prática 1

Nesta ficha prática faremos uma revisão sobre alguns dos conceitos básicos em Python que serão úteis no decorrer da disciplina. Haverão blocos de código preenchidos como explicação e haverão blocos em branco para que possa praticar. Revisaremos alguns conceitos e portanto caso ja tenha conhecimento sobre determinado comando aproveite a oportunidade para praticar.

# Prints e Strings

Print simples

In [21]:
#imprimir a string "Value"
print("Value")

Value


Print de uma variavel

In [22]:
#cria-se a variavel n e lhe atribui o valor 10
n = 10

#imprimir o valor contido na variavel n
print(n)

10


Print de um texto e uma variavel

In [23]:
#imprime o um string e logo em sequencia o valor da variavel n
print("Value =",n)

Value = 10


Fstring

In [24]:
#cria-se a variavel n
n = 10
#usando fstring para fazer a impressao do valor da variavel n anteriormente declarada. Utiliza-se "{variavel}" para indicar o local aonde deseja que a variavel apareça
print(f"Value = {n}")


Value = 10


**EXERCICIO 1**: Imprima a variavel abaixo com somente duas casas decimais usando fstring

In [25]:
x = 3.1456746
print()

# Listas, Matrizes e tuplas

Listas são definidas conforme descrito abaixo:


In [28]:
#cria-se uma lista utilizando os "[,]"
list1 = [1,2,3,4,5]
#imprime a lista
print(list1)

[1, 2, 3, 4, 5]


Pode-se usar operador (+) em listas:

In [31]:
#cria-se as duas listas
list1 = [1,2,3,4,5]
list2  = [5,6,7,8]

#imprime as duas listas somadas
print(list1+list2)
#numero 5 se repet. Aparece nas duas listas

[1, 2, 3, 4, 5, 5, 6, 7, 8]


Nesta disciplina trabalharemos com a biblioteca numpy quando formos usar listas:

In [64]:
#importar a biblioteca numpy e lhe atribuir o alias "np"
import numpy as np

Cria-se uma lista em numpy da seguinte forma:

In [17]:
#criando uma lista numpy
list1 = np.array([1,2,3,4,5])
#imprimindo a lista
print(list1)

[1 2 3 4 5]


Também é possivel converter listas python em listas numpy:

In [32]:
#Bloco lista python
#cria uma lista python
list1 = [1,2,3,4,5]
#imprime o conteúdo
print(list1)
#imprime o tipo
print(type(list1))

#separador
print("-"*10)

#bloco conversão
#converte a list1 em numpy
list1_np = np.array(list1)
#imprime o conteudo
print(list1_np)
#imprime o tipo
print(type(list1_np))

[1, 2, 3, 4, 5]
<class 'list'>
----------
[1 2 3 4 5]
<class 'numpy.ndarray'>


Trabalhar com listas numpy é mais rápido e ainda possuem os diversos atributos numpy.array:

In [46]:
#cria lista
list1 = np.array([1,3,2,5,4])
#a partir daqui para acessar os atributos basta colocar list1.(....)
print(f"Numero de dimensões: {list1.ndim}")
print(f"Forma: {list1.shape}") 
print(f"Valor Maximo: {list1.max()}")
print(f"Valor Minimo: {list1.min()}")
print(f"Soma: {list1.sum()}")

Numero de dimensões: 1
Forma: (5,)
Valor Maximo: 5
Valor Minimo: 1
Soma: 15


**EXERCICIO 2**: Crie uma matrix (lista de lista), de shape (3,2). Tal como o bloco acima calcule: numero de dimensões, shape, valor máximo, valor minimo e soma.

A forma ou o shape de uma lista ou matriz pode ser modificada pelo método reshape()

In [59]:
#cria lista
list1 = np.array([1,3,2,5,4,6])
print("Original:",list1)
print(list1.shape)
print()

#fazes o reshape dela para o formato (2,3)
list1_reshaped = list1.reshape((2,3))
print("Reshaped:",list1_reshaped)
print(list1_reshaped.shape)
print()

#faz o reshape novamente para que tenha somente 1 linha
list1_reshaped = list1_reshaped.reshape((6))
print("Igual a Original:",list1_reshaped)
print(list1_reshaped.shape)

Original: [1 3 2 5 4 6]
(6,)

Reshaped: [[1 3 2]
 [5 4 6]]
(2, 3)

Igual a Original: [1 3 2 5 4 6]
(6,)


**EXERCICIO 3**: Faça o reshape da matriz abaixo para (3,2).

In [60]:
list1 = np.array([1,3,2,5,4])
list1_reshaped = ....

Para acessar um endereço de um item de uma lista usa-se:

In [61]:
list1 = np.array([1,3,2,5,4,6])
print(list1[3])

5


**EXERCICIO 4**: Dada a matriz abaixo retorne o endereço do maior número

In [69]:
list1 = np.array([[1,3,2],[4,5,6],[6,0,2]])
print(np.argmax(list1))

# for....

5
