# Lab 2 - Rectangular data and Pandas

## Purpose
Give an introduction to  
* Jupyter Notebook
* Rectangular data
* Variables and records
* Independent and dependent variables
* Pandas and Numpy Libraries
* Exploratory Data Analysis

## Methodology
We will be using the Pandas library to load a dataset, perform operation and conduct some data analysis. Some challenges are presented at the end.

## Results
Some knowledge on how to load, write and manipulate rectangular data in Python. First hands on real data.

## Suggested next steps
Explore different types of data visualizations. Check [Python Graph Gallery](https://www.python-graph-gallery.com/) for ideas. This will be the topic of next week.


# Jupyter Notebooks

Anaconda will be our preference as a Python environment manager. If you haven't done it already, [install](https://www.anaconda.com/) it and follow the `intructions.md` file of the first week (available in moodle).

Jupyter Lab/Notebooks will be our IDE of preference.

Jupyter Notebooks are composed by Cells.

Cells can be either Markdown or Code.  

- Markdown cells allows us to write text, formulae, add images and explain things in the same way we would do in a normal notebook. Here is a [cheat sheet](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) for Markdown Sintax.

- Code Cells allows us to execute code.

Here is a Jupyter Notebook commands [cheat sheet](https://www.edureka.co/blog/wp-content/uploads/2018/10/Jupyter_Notebook_CheatSheet_Edureka.pdf) although you can also use the Help tab.

Useful Jupyter Notebook shortcuts:
- Esc and Enter to toggle between edit mode (notice how the colour of the cell on the left changes)
- A - new cell after current cell
- B - new cell before current cell
- Shit + Enter - execute cell and go to the next
- Ctrl + Enter - execute cell and remain on current
- DD - delete cell
- Z  - undo deleted

## Numpy

In [ ]:
import numpy as np

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. Also, it offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

## Before moving forward

Explore Numpy `dot` function

In [ ]:
v1 = [1,2,3,4]
v2 = [3,2,5,4]

# "np" is the alias for numpy library when imported like 'import numpy as np'
# print the dot product of v1 and v2 using numpy
# compare with the dot function you did in the last class


38

You can check [`numpy documentation`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html) or use the `help` function to understand more about any function

In [ ]:
help(np.dot)

Explore Numpy functions `linalg.norm` to obtain the magnitude/norm of the vectors `v1` and `v2`

In [ ]:
# compare with the norm function you did in the last class

Consider the cosine similarity function we build from scrach last week:

$$
  cos(v1, v2) = \frac{v1 . v2}{\lVert v1 \rVert \times \lVert v2 \rVert}
$$

Explore Numpy functions `linalg.norm` e `dot` and **re-write the cosine function** below without using a `for` loop.

## Rectangular data

A lot of the datasets we study in Data Science are rectangular, like a spreadsheet or database table. This means that we have a  `n` and `m` columns.

* A **column** in the table is commonly referred to as a **variable**.
    * You may also see them refered as: attribute, input, predictor or feature
* A **row** in the table is commonly referred to as a **record**.
    * You may also see them refered as: case, example, instance, observation, pattern or sample


<details>
<p>

> Rectangular data is essentially a two-dimensional matrix with rows indicating records and columns indicating variables
> -- <cite>[Peter Bruce, Andrew Bruce @ Practical Statistics for Data Scientists][3]</cite>

[3]: https://www.oreilly.com/library/view/practical-statistics-for/9781491952955/ch01.html

</p>
</details>

What are independent and dependent variables?  

<details>
<p>
    
- An **independent variable** is the variable that is changed or controlled in a scientific experiment to test the effects on the dependent variable.  
    
- A **dependent variable** is the variable being tested and measured in a scientific experiment.
    
</p>
</details>

Very often what we want to do in data science is to explain how the independent variables can control the dependent variable.

What other names are given to these variables?

<details>
<p>

> an **independent variable** is sometimes called a "predictor variable", regressor, covariate, "manipulated variable", "explanatory variable", exposure variable (see reliability theory), "risk factor" (see medical statistics), "feature" (in machine learning and pattern recognition) or "input variable".
> -- <cite>[Wikipedia][4]</cite>
    
> a **dependent variable** is sometimes called a "response variable", "regressand", "criterion", "predicted variable", "measured variable", "explained variable", "experimental variable", "responding variable", "outcome variable", "output variable", "target" or "label".
> -- <cite>[Wikipedia][4]</cite>

[4]: https://en.wikipedia.org/wiki/Dependent_and_independent_variables#Statistics_synonyms


    
</p>
</details>

## Pandas

In [ ]:
import pandas as pd

What is Pandas?

<details>
<p>

> Pandas is seriously a game changer when it comes to cleaning, transforming, manipulating and analyzing data. In simple terms, Pandas helps to clean the mess
> -- <cite>[Admond Lee][1]</cite>

[1]: https://towardsdatascience.com/why-and-how-to-use-pandas-with-large-data-9594dda2ea4c

</p>
</details>

Have a look at the Pandas documentation

<details>
<p>

> `pandas` is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.
> -- <cite>[pandas library][2]</cite>

[2]: https://pandas.pydata.org/

</p>

- API reference: https://pandas.pydata.org/docs/reference/index.html#api

### Lets use Pandas to create a retangular dataset

The DataFrame object is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table. It is generally the most commonly used pandas object.

#### Constructing DataFrame

A Pandas DataFrame can be constructed in a variety of ways.

One of them is from a list of dicts:

Let's create a DataFrame from a list of dictionaries. Each dictionary represents a record and the keys represent the variables.

Desired DataFrame:

```python
     a	b
0	0	0
1	1	2
2	2	4
```



In [ ]:
# create dataframe from a list of dictionaries to obtain the following output
#    a  b
# 0  0  0
# 1  1  2
# 2  2  4

# what should the items in the list be to obtain the output above?
data = []

# use pd.DataFrame to create a dataframe from the "data"

a  b
0  0  0
1  1  1
2  2  4

Pandas creates tabular data structures called DataFrames and missing values are represented as `NaN` (**Not a Number**)
- if you don't provide values for a column, pandas will fill it with `NaN`
- Handling missing values is a big part of data cleaning and preparation process and defining strategies to deal with them are really important.

In [ ]:
df = pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

A DataFrame object has has an `index` and a `column` attribute
- `index` indicates the start, end (exclusive) and increment of the row indices

RangeIndex(start=0, stop=2, step=1)

- `columns` indicates the **column names** of the DataFrame and can be used to access columns

**Casting to other data types** may help when working with those columns, try casting `df.columns` to a list

['a', 'b', 'c']

We can **rename** columns using the `rename` method

- Note that the columns were defined by the dictionary keys
- `inplace=True` will modify the DataFrame **in place**, otherwise a new DataFrame will be returned and the original will remain unchanged


In [ ]:
# before:
df = pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

In [ ]:
# after - use rename to rename the columns 'a' to 'data' and 'b' to 'science'



data  science    c
0   1.0        2  NaN
1   NaN        3  4.0

#### Creating your own DataFrame

Before learning more details and operations on DataFrames, lets create our own.

In [ ]:
#       name	shoe	height
#   0	ana	    38  	  168
#   1	bruno   39	    170
#   2	carlos	42	    174

name_list = []
shoe_list = []
height_list = []
gender_list = []

# we are going to create a dataframe from the lists above - what should be the "keys" and "values" of the dictionary?
students_df = pd.DataFrame({})
students_df

name  shoe  height
0     ana    38     168
1   bruno    39     170
2  carlos    42     174

Print the `columns` of the DataFrame

Index(['name', 'shoe', 'height', 'gender'], dtype='object')

Print the `index` of the DataFrame

RangeIndex(start=0, stop=3, step=1)

We forgot the **gender data**. This is how we can add a new column to the DataFrame after it has been created

name  shoe  height  gender
0     ana    38     168  female
1   bruno    39     170    male
2  carlos    42     174    male

We may have also introduced a wrong value. We can **access** it or **change** it using `loc`

In [ ]:
students_df.loc[2]

name      carlos
shoe          42
height       174
gender      male
Name: 2, dtype: object

We can also use the `iloc` method to access data by **position**
- use `iloc` to access the last row of the DataFrame

- Use `iloc` to access the last element of the last column of the DataFrame
    
    - **Tip**: the DataFrame is matrix-like, so you can use the same indexing as you would use in a matrix (even negative indices work)

## Write and Read a csv file

We can use Pandas to perform both operations.
Run the cell below and check on your folder if the file was created.

In [ ]:
# write a DataFrame as a csv file


Read a csv file into a DataFrame - by **default**, `read_csv` assumes that the **delimiter is a comma**

In [ ]:
# read the csv file into students_df2
students_df2 =

Let's check if `students_df` is equal to `students_df2` using `.equals` method

When saving a DataFrame to a csv file, we can specify the `index` (`True` | `False`)

## Operations on pandas DataFrames

In this section you will learn about some DataFrame methods like `head` and `tail`.

### Subset of rows (records)

#### Select the first n rows

name  shoe  height  gender
0    ana    38     168  female
1  bruno    39     170    male

#### Select the last rows

name  shoe  height gender
1   bruno    39     170   male
2  carlos    42     174   male

#### Get a random sample of n rows

name  shoe  height  gender
2  carlos    42     174    male
0     ana    38     168  female

#### Select rows by position
- select the **first and second rows**

name  shoe  height gender
1   bruno    39     170   male
2  carlos    42     174   male

#### Select rows that meet logical criteria
- select all students with `height` of **170cm or higher**

name  shoe  height gender
1   bruno    39     170   male
2  carlos    42     174   male

#### Select rows based on multiple conditions
- select all `male` students with `height` of **172cm or higher**

name  shoe  height gender
2  carlos    42     174   male

- select all `female` students with `height` of **172cm or higher**

name  shoe  height  gender
0     ana    38     168  female
2  carlos    42     174    male

### Subset of columns (variables)

#### Select columns by name

0       ana
1     bruno
2    carlos
Name: name, dtype: object

Select subset of columns `name` and `gender`

name  gender
0     ana  female
1   bruno    male
2  carlos    male

#### Select columns by position
Using `iloc[rows, columns]` to select
- select the **first and third columns** of the dataframe

shoe  gender
0    38  female
1    39    male
2    42    male

### Subset of both rows and columns
- select the rows where the `shoe` size is **greater than 40** and **only** the columns `name` and `shoe`

name  shoe
2  carlos    42

### Summing Up

* When selecting subsets of data, square brackets `[]` are used.
* Inside these brackets, you can use a single column/row label, a list of column/row labels, a slice of labels, a conditional expression or a column.
* Select specific rows and/or columns using **loc** when using the row and column names.
* Select specific rows and/or columns using **iloc** when using the positions in the table.
* You can assign new values to a selection based on **loc/iloc**.

[This](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf) Pandas Cheat Sheet might come in handy.

## Challenges

In these challenges you will handle a bigger dataset.

There are a few first questions you need to know how to answer before reading a CSV file with Pandas

- Does the CSV have a header line?
- Is there an index column?
- What is the separator character on the CSV file?
- If there are missing values, is there any specific word being used to describe a missing value?

Then, these details can be handled by specifing some parameters as `sep`, `na_values` or `index_col`.

### Challenge 1 - Load the dataset

In [ ]:
# Your code here
# load titanic dataset

### Challenge 2 - Validate the loading

1. Show the first 10 rows and confirm if the table matches with the lines


In [ ]:
# Your code here

2. Try the DataFrame method `info`. It is a nice alternative. What information do you get from this?

In [ ]:
# Your code here

### Challenge 3 - Some basic EDA

**EDA** stands for `Exploratory Data Analysis`. It is used by data scientists to analyze and investigate data sets and summarize their main characteristics, often employing data visualization methods.

Try executing `df_titanic.describe()`.

In [ ]:
# Your code here

After investigating the results, describe them and comment on the usefulness of this Pandas function.

In [ ]:
# Your comments here

Now, try `.info()` method.

In [ ]:
# Your code here

What information do you get from this?

In [ ]:
# Your comments here

### Challenge 4 - Getting to know your data

What do the results above tell you about each variable? Do you actually now what they mean?

This is a crutial step. For info on this dataset click [here](https://www.kaggle.com/competitions/titanic/data?select=train.csv).



In [ ]:
# Your comments here

---

## Additional Challenge

This challenge is solved to help you get familiar with the most important object of the NumPy library, the array.

### Part I

1. Use the numpy's function `arange` and create the array `my_array` with the sequence of numbers from 0 to 24.

2. Use the method `reshape` to redimension the array so that it has 6 rows and 4 columns. What happened? What is the relasionship between the number of elements and the dimensions of a 2D matrix?

In [ ]:
my_array = np.arange(24).reshape((6,4))
my_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

###  Part II

$$\begin{bmatrix}
1 & 2 & 1 & 7 \\
3 & 0 & 1 & 8 \\
0 & 2 & 4 & 9 \\
2 & 2 & 5 & 5
\end{bmatrix}$$

1. Create this matrix in NumPy

2. Slice the first column

3. Slice the first column, but only the second and third rows

4. Slice the 4 elements at the center of the matrix

5. Slice the sub-matrix of the 4 elements of the lower right corner, without using the matrix size

6. Slice the sub-matrix of the 4 elements of the upper right corner, without using the matrix size

**Expected output**:

```python

first column:
 [1 3 0 2]

first column, rows 2 and 3:
 [3 0]

centre:
 [[0 1]
 [2 4]]

bottom right:
 [[4 9]
 [5 5]]

bottom right:
 [[4 9]
 [5 5]]

top right:
 [[1 7]
 [1 8]]

top right:
 [[1 7]
 [1 8]]

top right:
 [[1 7]
 [1 8]]
```